# Generated by Django 4.2.1 on 2023-05-26 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=60)),
                ('LastName', models.CharField(default='', max_length=60)),
                ('Email', models.EmailField(default='', max_length=254, unique=True)),
                ('Adress', models.CharField(default='', max_length=60)),
                ('City', models.CharField(default='', max_length=60)),
                ('StateProvince', models.CharField(default='', max_length=60)),
                ('phoneNumber', models.TextField(default='', max_length=13)),
                ('username', models.CharField(default='', max_length=60)),
                ('password', models.CharField(default='', max_length=20)),
                ('image', models.URLField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('OrderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=60)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estinscrit', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('description', models.TextField(default='', max_length=60)),
                ('price', models.FloatField(default=0)),
                ('qteStock', models.IntegerField(default=0)),
                ('image', models.URLField(default='', max_length=60)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_debit_card_number', models.TextField(default='')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('security_code', models.IntegerField(default=0)),
                ('billing_address', models.TextField(default='')),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_produit', models.IntegerField(default=0)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('produit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.client')),
            ],
        ),
    ]
