# Generated by Django 4.2.1 on 2023-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Adress',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='StateProvince',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.URLField(max_length=60),
        ),
    ]
