# Generated by Django 4.2.1 on 2023-05-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_client_adress_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='FirstName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='LastName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.TextField(max_length=13),
        ),
    ]
