# Generated by Django 4.2.1 on 2023-05-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_client_firstname_alter_client_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
