# Generated by Django 4.2.1 on 2023-06-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_client_image_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='LastName',
        ),
    ]
