# Generated by Django 4.2.1 on 2023-06-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_firstname_client_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Email',
        ),
    ]
