# Generated by Django 4.2.1 on 2023-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='FullName',
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default='', max_length=60),
        ),
    ]
