# Generated by Django 4.2.1 on 2023-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_client_adress_remove_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Adress',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='City',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='StateProvince',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.TextField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
    ]
