# Generated by Django 4.2.1 on 2023-06-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Adress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='City',
        ),
    ]
