# Generated by Django 4.2.1 on 2023-06-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_client_adress_remove_client_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='StateProvince',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
