# Generated by Django 4.2.1 on 2023-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_client_stateprovince_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Adress',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='City',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='StateProvince',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNumber',
            field=models.TextField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
    ]
