# Generated by Django 4.2.1 on 2023-06-01 22:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_client_adress_client_city_client_stateprovince_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payement',
            old_name='client',
            new_name='customer',
        ),
    ]
