# Generated by Django 4.2.1 on 2023-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_client_customer_rename_client_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='LastName',
        ),
    ]
