# Generated by Django 4.2.1 on 2023-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_firstname_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
