# Generated by Django 4.2.1 on 2023-06-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
    ]
