# Generated by Django 4.2.1 on 2023-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
    ]
