# Generated by Django 4.2.1 on 2023-06-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
