# Generated by Django 4.2.1 on 2023-06-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_customer_password_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.produit'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
    ]
