# Generated by Django 4.2.1 on 2023-06-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_cart_produit_cart_quantity_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totalPrice',
            new_name='price',
        ),
    ]
