# Generated by Django 4.2.1 on 2023-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
    ]
